name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download
        run: |
          wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5-cross/gcc-5-cross-base_5.5.0-12ubuntu1cross1_all.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5-cross/libhfubsan0-armel-cross_5.3.1-14ubuntu2cross1_all.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5-cross/libhfasan2-armel-cross_5.3.1-14ubuntu2cross1_all.deb 
          wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5-cross/libhfgcc-5-dev-armel-cross_5.3.1-14ubuntu2cross1_all.deb 
          wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5-cross/libgcc-5-dev-armel-cross_5.3.1-14ubuntu2cross1_all.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5-cross/libstdc++-5-dev-armel-cross_5.3.1-14ubuntu2cross1_all.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5-cross/libhfstdc++-5-dev-armel-cross_5.3.1-14ubuntu2cross1_all.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5-cross/libhfasan2-armel-cross_5.3.1-14ubuntu2cross1_all.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5-cross/gcc-5-multilib-arm-linux-gnueabi_5.3.1-14ubuntu2cross1_amd64.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5-cross/g++-5-multilib-arm-linux-gnueabi_5.3.1-14ubuntu2cross1_amd64.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5-cross/gcc-5-arm-linux-gnueabi-base_5.3.1-14ubuntu2cross1_amd64.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5-cross/cpp-5-arm-linux-gnueabi_5.3.1-14ubuntu2cross1_amd64.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5-cross/libubsan0-armel-cross_5.3.1-14ubuntu2cross1_all.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5-cross/libasan2-armel-cross_5.3.1-14ubuntu2cross1_all.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5-cross/libgcc-5-dev-armel-cross_5.3.1-14ubuntu2cross1_all.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5-cross/gcc-5-arm-linux-gnueabi_5.3.1-14ubuntu2cross1_amd64.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5-cross/libstdc++-5-dev-armel-cross_5.3.1-14ubuntu2cross1_all.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5-cross/g++-5-arm-linux-gnueabi_5.3.1-14ubuntu2cross1_amd64.deb
      - name: Install
        run: |
          sudo apt install ./gcc-5-cross-base_5.5.0-12ubuntu1cross1_all.deb -y
          sudo apt install ./libhfubsan0-armel-cross_5.3.1-14ubuntu2cross1_all.deb -y
          sudo apt install ./libhfasan2-armel-cross_5.3.1-14ubuntu2cross1_all.deb -y
          sudo apt install ./libhfgcc-5-dev-armel-cross_5.3.1-14ubuntu2cross1_all.deb -y
          sudo apt install ./libubsan0-armel-cross_5.3.1-14ubuntu2cross1_all.deb -y
          sudo apt install ./libasan2-armel-cross_5.3.1-14ubuntu2cross1_all.deb -y
          sudo apt install ./libgcc-5-dev-armel-cross_5.3.1-14ubuntu2cross1_all.deb -y
          sudo apt install ./libstdc++-5-dev-armel-cross_5.3.1-14ubuntu2cross1_all.deb -y
          sudo apt install ./libhfstdc++-5-dev-armel-cross_5.3.1-14ubuntu2cross1_all.deb -y
          sudo apt install ./libhfasan2-armel-cross_5.3.1-14ubuntu2cross1_all.deb -y
          sudo apt install ./gcc-5-arm-linux-gnueabi-base_5.3.1-14ubuntu2cross1_amd64.deb -y
          sudo apt install ./gcc-5-arm-linux-gnueabi_5.3.1-14ubuntu2cross1_amd64.deb -y
          sudo apt install ./gcc-5-multilib-arm-linux-gnueabi_5.3.1-14ubuntu2cross1_amd64.deb -y
          sudo apt install ./g++-5-multilib-arm-linux-gnueabi_5.3.1-14ubuntu2cross1_amd64.deb -y
          sudo apt install ./cpp-5-arm-linux-gnueabi_5.3.1-14ubuntu2cross1_amd64.deb -y
          sudo apt install ./libstdc++-5-dev-armel-cross_5.3.1-14ubuntu2cross1_all.deb -y
          sudo apt install ./g++-5-arm-linux-gnueabi_5.3.1-14ubuntu2cross1_amd64.deb -y
      - name: Check
        run: |
          arm-linux-gnueabi-gcc-5 -v
          arm-linux-gnueabi-g++-5 -v
